{
 "title": "K-SISS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(tgi_request_mean_time_per_token_duration_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU resource usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "KubeComp_gpu_resource", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Performance metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(tgi_request_mean_time_per_token_duration_sum[1m])/increase(tgi_request_mean_time_per_token_duration_count[1m])",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}